/**
 * Saydo Animation Configuration
 * Centralized animation constants and spring values
 */

// CSS Spring easing functions generated by Motion Dev
export const springs = {
  // Snappy spring for UI interactions (0.25 bounce, 0.4s perceptual duration)
  snappy: "550ms linear(0, 0.1719, 0.4986, 0.7952, 0.9887, 1.0779, 1.0939, 1.0726, 1.0412, 1.0148, 0.9986, 0.9919, 0.9913, 0.9937, 0.9967, 0.999, 1.0003, 1)",
  
  // Gentle spring for subtle animations (0.15 bounce, 0.5s)
  gentle: "600ms linear(0, 0.1116, 0.3464, 0.5762, 0.7552, 0.8759, 0.9493, 0.9889, 1.0069, 1.0115, 1.0087, 1.0034, 0.9992, 0.9972, 0.9971, 0.9981, 0.9992, 1)",
  
  // Bouncy spring for emphasis (0.35 bounce, 0.5s)
  bouncy: "650ms linear(0, 0.1462, 0.4264, 0.6859, 0.8659, 0.9682, 1.0235, 1.0473, 1.0485, 1.0362, 1.0182, 1.0027, 0.9927, 0.9884, 0.9878, 0.9896, 0.9926, 0.9958, 0.9983, 1)",
  
  // Quick spring for micro-interactions (0.2 bounce, 0.25s)
  quick: "350ms linear(0, 0.2204, 0.5953, 0.8684, 1.0000, 1.0485, 1.0485, 1.0229, 1.0000, 0.9917, 0.9917, 0.9959, 1)",
} as const

// GSAP easing presets
export const gsapEase = {
  // Smooth easing for entrances
  smoothOut: "power2.out",
  smoothInOut: "power2.inOut",
  
  // Expressive easing for key moments
  expressiveOut: "power3.out",
  expressiveInOut: "power3.inOut",
  
  // Elastic for playful animations
  elastic: "elastic.out(1, 0.5)",
  elasticGentle: "elastic.out(1, 0.75)",
  
  // Back easing for overshoots
  backOut: "back.out(1.7)",
  backInOut: "back.inOut(1.7)",
  
  // Custom bezier for hero text
  heroReveal: "power4.out",
} as const

// Animation durations (in seconds for GSAP)
export const durations = {
  instant: 0.15,
  fast: 0.25,
  normal: 0.4,
  slow: 0.6,
  dramatic: 0.8,
  
  // Stagger delays
  staggerTight: 0.03,
  staggerNormal: 0.08,
  staggerRelaxed: 0.12,
} as const

// ScrollTrigger defaults
export const scrollTriggerDefaults = {
  start: "top 85%",
  end: "bottom 20%",
  toggleActions: "play none none none",
  fastScrollEnd: true,
  preventOverlaps: true,
} as const

// Viewport breakpoints for responsive animations
export const breakpoints = {
  mobile: 640,
  tablet: 768,
  desktop: 1024,
  wide: 1280,
} as const

// Animation distance values
export const distances = {
  subtle: 10,
  normal: 20,
  dramatic: 40,
  heroic: 60,
} as const

// Glow and shadow values for teal theme
export const glowEffects = {
  primary: {
    subtle: "0 0 20px rgba(13, 148, 136, 0.15)",
    medium: "0 0 40px rgba(13, 148, 136, 0.25)",
    strong: "0 0 60px rgba(13, 148, 136, 0.4)",
  },
  rose: {
    subtle: "0 0 20px rgba(244, 63, 94, 0.15)",
    medium: "0 0 40px rgba(244, 63, 94, 0.25)",
    strong: "0 0 60px rgba(244, 63, 94, 0.4)",
  },
} as const

// Particle configuration for hero background
export const particleConfig = {
  desktop: {
    count: 30,
    sizeRange: [4, 8],
    speedRange: [15, 30],
    opacityRange: [0.3, 0.6],
  },
  mobile: {
    count: 12,
    sizeRange: [3, 6],
    speedRange: [20, 35],
    opacityRange: [0.2, 0.4],
  },
} as const

// Check if reduced motion is preferred
export const prefersReducedMotion = (): boolean => {
  if (typeof window === "undefined") return false
  return window.matchMedia("(prefers-reduced-motion: reduce)").matches
}

// Get responsive particle config
export const getParticleConfig = () => {
  if (typeof window === "undefined") return particleConfig.desktop
  return window.innerWidth < breakpoints.tablet 
    ? particleConfig.mobile 
    : particleConfig.desktop
}







