/**
 * Landing page image URLs and paths
 * This file is auto-generated by scripts/generate-landing-images.ts
 * Update the URLs after running the image generation script
 */

import { getImagePublicUrl } from "./storage-urls"
import landingImagesJson from "./landing-images.json"

export type LandingImageKey =
  | "before-after-comparison"
  | "how-it-works-visual"
  | "ai-agent-workflow"
  | "agent-vs-transcription"
  | "use-case-healthcare"
  | "use-case-founder"
  | "use-case-caregiver"
  | "use-case-writer"
  | "use-case-technician"

interface ImageData {
  url: string
  path: string
}

const images = landingImagesJson as Record<LandingImageKey, ImageData>

/**
 * Get the public URL for a landing page image
 * Falls back to constructing the URL from the path if url is empty
 * This allows images to work even before they're generated (if they exist in storage)
 */
export function getLandingImageUrl(key: LandingImageKey): string {
  const image = images[key]
  if (!image) {
    console.warn(`Image key "${key}" not found`)
    return ""
  }

  // If URL is set, use it (from generated images)
  if (image.url && image.url.trim() !== "") {
    return image.url
  }

  // Otherwise, construct from path (works if images are already in Supabase Storage)
  try {
    return getImagePublicUrl(image.path)
  } catch (error) {
    console.warn(`Failed to get image URL for ${key}:`, error)
    // Return a placeholder or empty string
    return ""
  }
}

/**
 * Get all landing page images
 */
export function getAllLandingImages(): Record<LandingImageKey, ImageData> {
  return images
}

